apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: uber-mini

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shankerp/uber-mini:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: uber-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: uber-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uber-secret
                  key: POSTGRES_PASSWORD

